### PR TITLE
Add annotation functions for unrooted tree layouts and other fixes. 

### PR DESCRIPTION
**Pull request by JustGitting**
Hi,

I've added/modified the annotation functions to annotate the clades of the unrooted tree layouts. I've also fixed the labels for unrooted trees so they are easier to read.

Cheers,
JG

### CODE REVIEW

**Comment by GuangchuangYu** [comment]
Can you explain why you change the parameter at <https://github.com/GuangchuangYu/ggtree/pull/152/files#diff-b67b4c9e48f0ba337b73d00861518a6fR41>?

**Comment by GuangchuangYu** [comment]
FYI: I have fixed the R check <https://github.com/GuangchuangYu/ggtree/commit/9653250666d21c4b8596bf6cbb273bf1e88f7293>.

BTW: You can add your name in author list <https://github.com/GuangchuangYu/ggtree/blob/master/DESCRIPTION#L6-L10>.

**Comment by JustGitting** [comment]
> Can you explain why you change the parameter at https://github.com/GuangchuangYu/ggtree/pull/152/files#diff-b67b4c9e48f0ba337b73d00861518a6fR41?

If you mean this function: 

`getMRCA.df_internal <- function(data, tip1, tip2) `
to
`getMRCA.df_internal <- function(data, tip, anc) {`

I only changed the parameter names that made it clearer what the parameters meant. My understand was that "tip" is a tree tip and "anc" is the tips ancester. I felt it was a bit better than tip1 and tip2... but I could be wrong, please change back if you need to.

**Comment by GuangchuangYu** [comment]
I change them to `node1` & `node2`, see <https://github.com/GuangchuangYu/ggtree/commit/07063f95a74aee6b9c965efae96f9c99c6d1006c>.

**Pull request merged**
